// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `PetFoodSensor.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.ice.android.petfood.slice.PetFoodSensors;

public class _SensorControlPrxI extends com.zeroc.Ice._ObjectPrxI implements SensorControlPrx
{
    public static final long serialVersionUID = 0L;
}
