// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `PetFoodSensor.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.ice.android.petfood.slice.PetFoodSensors;

public interface SensorControlPrx extends com.zeroc.Ice.ObjectPrx
{
    default void motorTime(String time)
    {
        motorTime(time, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void motorTime(String time, java.util.Map<String, String> context)
    {
        _iceI_motorTimeAsync(time, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> motorTimeAsync(String time)
    {
        return _iceI_motorTimeAsync(time, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> motorTimeAsync(String time, java.util.Map<String, String> context)
    {
        return _iceI_motorTimeAsync(time, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_motorTimeAsync(String iceP_time, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "motorTime", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_time);
                 }, null);
        return f;
    }

    default void givefood(int weight)
    {
        givefood(weight, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void givefood(int weight, java.util.Map<String, String> context)
    {
        _iceI_givefoodAsync(weight, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> givefoodAsync(int weight)
    {
        return _iceI_givefoodAsync(weight, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> givefoodAsync(int weight, java.util.Map<String, String> context)
    {
        return _iceI_givefoodAsync(weight, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_givefoodAsync(int iceP_weight, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "givefood", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeInt(iceP_weight);
                 }, null);
        return f;
    }

    default int getContainerFood()
    {
        return getContainerFood(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int getContainerFood(java.util.Map<String, String> context)
    {
        return _iceI_getContainerFoodAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> getContainerFoodAsync()
    {
        return _iceI_getContainerFoodAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> getContainerFoodAsync(java.util.Map<String, String> context)
    {
        return _iceI_getContainerFoodAsync(context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> _iceI_getContainerFoodAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getContainerFood", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    default int getFoodEated()
    {
        return getFoodEated(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int getFoodEated(java.util.Map<String, String> context)
    {
        return _iceI_getFoodEatedAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> getFoodEatedAsync()
    {
        return _iceI_getFoodEatedAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> getFoodEatedAsync(java.util.Map<String, String> context)
    {
        return _iceI_getFoodEatedAsync(context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> _iceI_getFoodEatedAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getFoodEated", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    default boolean eatingNow()
    {
        return eatingNow(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean eatingNow(java.util.Map<String, String> context)
    {
        return _iceI_eatingNowAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> eatingNowAsync()
    {
        return _iceI_eatingNowAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> eatingNowAsync(java.util.Map<String, String> context)
    {
        return _iceI_eatingNowAsync(context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_eatingNowAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "eatingNow", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default int getWeight()
    {
        return getWeight(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int getWeight(java.util.Map<String, String> context)
    {
        return _iceI_getWeightAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> getWeightAsync()
    {
        return _iceI_getWeightAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> getWeightAsync(java.util.Map<String, String> context)
    {
        return _iceI_getWeightAsync(context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> _iceI_getWeightAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getWeight", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SensorControlPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), SensorControlPrx.class, _SensorControlPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SensorControlPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), SensorControlPrx.class, _SensorControlPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SensorControlPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), SensorControlPrx.class, _SensorControlPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SensorControlPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), SensorControlPrx.class, _SensorControlPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static SensorControlPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, SensorControlPrx.class, _SensorControlPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static SensorControlPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, SensorControlPrx.class, _SensorControlPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default SensorControlPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (SensorControlPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default SensorControlPrx ice_adapterId(String newAdapterId)
    {
        return (SensorControlPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default SensorControlPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (SensorControlPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default SensorControlPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (SensorControlPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default SensorControlPrx ice_invocationTimeout(int newTimeout)
    {
        return (SensorControlPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default SensorControlPrx ice_connectionCached(boolean newCache)
    {
        return (SensorControlPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default SensorControlPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (SensorControlPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default SensorControlPrx ice_secure(boolean b)
    {
        return (SensorControlPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default SensorControlPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (SensorControlPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default SensorControlPrx ice_preferSecure(boolean b)
    {
        return (SensorControlPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default SensorControlPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (SensorControlPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default SensorControlPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (SensorControlPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default SensorControlPrx ice_collocationOptimized(boolean b)
    {
        return (SensorControlPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default SensorControlPrx ice_twoway()
    {
        return (SensorControlPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default SensorControlPrx ice_oneway()
    {
        return (SensorControlPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default SensorControlPrx ice_batchOneway()
    {
        return (SensorControlPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default SensorControlPrx ice_datagram()
    {
        return (SensorControlPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default SensorControlPrx ice_batchDatagram()
    {
        return (SensorControlPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default SensorControlPrx ice_compress(boolean co)
    {
        return (SensorControlPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default SensorControlPrx ice_timeout(int t)
    {
        return (SensorControlPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default SensorControlPrx ice_connectionId(String connectionId)
    {
        return (SensorControlPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default SensorControlPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (SensorControlPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::PetFoodSensors::SensorControl";
    }
}
